### ISSUE TITLE
Boolean operations API

### ISSUE THREAD

**Issue by petrbrzek** [Pomax/bezierjs#10]
Would be great to expose boolean methods (AND, OR, NOT, XOR, ...) like you describe in http://pomax.github.io/bezierinfo/.

**Comment by Pomax** [comment]
agreed, making as enhancement, although I've been unhappy with the code that's been in place on bezierinfo for quite a while now. I need to find some time to actually write a better implementation, but that time's hard to come by.

**Comment by jarek-foksa** [comment]
@Pomax What is wrong with the existing implementation you have done in Processing? Does it fail with some edge cases?

**Comment by Pomax** [comment]
yeah, it doesn't deal with colinear or point incidence, it forms rather weird things

**Comment by jarek-foksa** [comment]
What do you think about VectorBoolean library that is used by Sketch.app? The library was initially written in Objective-C, but there is a [Swift port](https://github.com/lrtitze/Swift-VectorBoolean) which should be rather easy to port to JavaScript.

I was also thinking about porting the new intersection graph from [2Geom](http://bazaar.launchpad.net/~lib2geom-hackers/lib2geom/trunk/view/head:/src/2geom/intersection-graph.cpp). Both VectorBoolean and 2Geom implementations look solid, but I find the 2Geom C++ code much harder to understand.

**Comment by Pomax** [comment]
honestly at this point I'm using [paper.js](http://paperjs.org/) for shape operations, as it has pretty well implemented boolean operation support.

**Comment by jarek-foksa** [comment]
@Pomax Thanks for hint, I wasn't aware of the recent improvements to Paper.js, it looks like it can handle almost all edge cases now.

**Comment by Pomax** [comment]
closing as I'm using paper.js for this myself.
