### ISSUE TITLE
Find optimal segmentation for getLUT

### ISSUE THREAD

**Issue by infusion** [Pomax/bezierjs#101]
Hello Pomax,

big thanks for making this high quality library and the bezier info document available. `getLUT` for curve flattening is pretty good already, but I wonder if there is a better curve approximation by sampling not linearly over `t` but those points leaving the minimal amount of points for a line segment approximation. If there were a solution for this, it would be a nice default value for `getLUT` or a new `flatten` method maybe. What do you think about this?

Robert

**Comment by Pomax** [comment]
flattening based on curvature is entirely possible, the main benefit of the current implementation is it's "dumb, and fast": computing the curvature at a t value to predict which next one to sample is generally more expensive than just iterating 10 more times, so if you want to play around with better flattening policies I'll be happy to add them in, but in terms of getting a LUT, "dumb but fast" tends to be super useful already =)

**Comment by infusion** [comment]
Hmm, you might be right, that such a naive approach works reasonable well for most applications. I just used it in my project and don't see any performance problems, not as I assumed initially

Over-sampling and filtering (with simplify.js for example) also sounds like a good idea for projects where offline-processing is possible.

**Comment by Pomax** [comment]
or even parallel processing: it is unlikely your code is constantly working, so you can schedule optimizations in the background and run them when the rest of your code's just sitting idle.
