### ISSUE TITLE
No API docs

### ISSUE THREAD

**Issue by sanyabeast** [Pomax/bezierjs#103]
No api documentation, even no arguments description. 
Only funny demo for dummies.
var curve = new Bezier(100,25 , 10,90 , 110,100 , 150,195);
What is fisrt argument? What is second one? Third? Fourth?
Should I make a reverse engeneeringto know?

**Comment by Pomax** [comment]
if you can't be assed to be polite, I have no reason to be polite either. Maybe read http://pomax.github.io/bezierjs/ which OH LOOK EXPLAINS THAT.
