### ISSUE TITLE
Interacting with `.project()` demo causes incorrect behavior

### ISSUE THREAD

**Issue by jconst** [Pomax/bezierjs#105]
Initially, this issue made me think that `project()` itself was broken in the library. But in fact, the interactive demo on https://pomax.github.io/bezierjs/ just doesn't respond correctly to having the points moved around.

Essentially, it looks like the `t` value returned will be based on the original curve from when the page loaded, not the one that is currently closest to the mouse pointer after having moved the bezier around:
![project](https://user-images.githubusercontent.com/291149/48017036-35461a80-e0fb-11e8-8428-918599c106b5.gif)

The exception seems to be when the mouse is closest to one of the end points. In this case, it looks correct.

A quick and easy fix would just be to disable interaction for this demo, and of course the ideal fix would be for the demo to respond correctly to changing the bezier. This is probably pretty low-priority, but I did spend a good amount of time trying to figure out what was going on here, thinking I might have to implement project() myself, so this bug might have a bigger impact than expected.

**Comment by Pomax** [comment]
Ah, I probably forget to call curve.update(), let me see what's up with that.

**Comment by Pomax** [comment]
fixed, thanks for letting me know! (the .update() function wasn't invalidating any precomputed LUT).
