### ISSUE TITLE
Consider using semver philosophy for breaking changes.

### ISSUE THREAD

**Issue by Tom32i** [Pomax/bezierjs#106]
Changes such as [this one](https://github.com/Pomax/bezierjs/commit/da596e1ed05c8ce4cbe0a7d0e26711ff7fd5c536#diff-c1129c8b045390789fa8ff62f2c6b4a9R36), made between `v2.2.8` and `v2.2.9` introduce a breaking change in the API:

```diff
- Bezier.fromSVG("M 0 0 Q 0.5 1 1 0")
+ Bezier.SVGtoBeziers("M 0 0 Q 0.5 1 1 0").curve(0)
```

According to [semver](https://semver.org/): this should result in a major change, not a patch (in this case: `v2.2.8` to `v3.0.0`).

Package managers like NPM or Yarn use this semantic versioning and never move to a major version when you install or update you projet dependencies, so that your code doesn't break.
But this only work if packages declare breaking changes with a major version update.

__Would you consider following the semantic versioning philosophy in bezierjs?__

Thomas,
A happy user of bezierjs.

**Comment by Pomax** [comment]
I did. That function is not part of the public API in the slightest. Use any function that you find but isn't in the official API docs at your own risk.
