### ISSUE TITLE
Seeking input on new library based on Bezier.js

### ISSUE THREAD

**Issue by aab29** [Pomax/bezierjs#108]
Hey @Pomax !  Sorry this was the only way I can think of to reach you.  It's Aaron Barrett here, regarding bezier.dart.  I hope you're doing well, and sorry if I'm bugging you.  I just want to make sure you've been getting my emails. 📧  Have you had a chance to look at the library at all, or would you like more time?  Are you okay with our attributions?  Any other thoughts on the library?  Just want me to leave you alone?  😅  Whatever the case that's fine, but I wanted to give you a chance to have your say before I publish anything.  Thank you!  ✌️

**Comment by Pomax** [comment]
Heya, I've been super busy, I'll give it a look-over this weekend!

**Comment by aab29** [comment]
Thanks again for your help, @Pomax .  bezier.dart is [live](https://pub.dartlang.org/packages/bezier)!  🚀 The announcement is [here](http://www.dartographer.com/announcing-bezier.dart/), and the project page is [here](http://www.dartographer.com/bezier/).

...And here's a fun little [example animation](http://www.dartographer.com/apps/bezier_dart_example/web/index.html).  🙃
