### ISSUE TITLE
offset bug on nearly-straight curve

### ISSUE THREAD

**Issue by ensconced** [Pomax/bezierjs#110]
This curve...

```javascript
const bezier = new Bezier(601, 251, 617.3172782509446, 233.5695255356486, 633.6345565018889, 216.13905107129727, 651, 201);
```
...gives a messed up offset (regardless of offset sign or magnitude).

Here the bezier is in red, offset in blue:
![offset bug](https://i.imgur.com/GOB6Y5J.png)

Demo here:  https://codepen.io/barnettjoe/pen/WPxamx

Docking just one decimal point from `617.3172782509446` fixes this, but I can't tell whether rounding will consistently prevent this from happening.

**Comment by ensconced** [comment]
This seems to be a result of `bezier.reduce()` producing a large number of very short curves, which end up scaling in the wrong direction.

**Comment by Pomax** [comment]
Yeah, there are bugs around (near as makes no difference) degenerate curve at the moment. See https://github.com/Pomax/bezierjs/issues/37 and https://github.com/Pomax/bezierjs/issues/102
