### ISSUE TITLE
utils.dist() only calculates 2d distance

### ISSUE THREAD

**Issue by Luzzifus** [Pomax/bezierjs#115]
utils.dist (@ line 270): The function only uses x- and y- coordinates for the distance and ignores z, which leads to wrong results of e.g. .project() in some cases when working with 3D beziers.

**Comment by Pomax** [comment]
There's a lot of functions that only work in 2D, but dist shouldn't be one of those. Thanks for letting me know

**Comment by Luzzifus** [comment]
Well since you added the "help wanted" tag, the fix is a very easy one:

```
dist: function(p1, p2) {  
  var dx = p1.x - p2.x,  
    dy = p1.y - p2.y,  
    dz = (p1.z || 0) - (p2.z || 0);   
  return sqrt(dx * dx + dy * dy + dz * dz);  
},
```

**Comment by Pomax** [comment]
that would have been better as a PR (anyone can file a PR on github, just visit the file, click "edit", and github will let you form a PR without ever having to manually clone the repo or edit a file in a local code editor, you can do the entire start-to-finish on github.com), but now that I actually had some time to look at the bezier repos: agreed, pushed v2.4.2 with that fix.
