### ISSUE TITLE
Bug in .project(point)

### ISSUE THREAD

**Issue by lizardking** [Pomax/bezierjs#120]
Hi
There seems to be a small bug in .project(point). 
The following part of the code ([line 267 and following in bezier.js](https://github.com/Pomax/bezierjs/blob/master/lib/bezier.js#L267)) returns the position of the start or the end of the curve even if these points are not the closest points, e.g. if the clostest point in the middle between the start of the curve and the next LUT point the function returns the start instead of the middle point).

```javascript
if (mpos === 0 || mpos === l) {
  var t = mpos / l,
  pt = this.compute(t);
  pt.t = t;
  pt.d = mdist;
  return pt;
}
```

The bug is easy to reproduce and detect if a small number of lut points (e.g. 10) is used. Like this the calculated closest point suddenly jumps to the start or the end of the curve.

**Comment by Pomax** [comment]
fixed in 2.5.1 by removing that "optimization"
