### ISSUE TITLE
How to properly destroy the bezier object?

### ISSUE THREAD

**Issue by yellow1912** [Pomax/bezierjs#125]
Should I just set it to null and let the garbage collector does the job?

**Comment by Pomax** [comment]
JS auto-collects things that have dropped out of scope, its programming model is such that if you're trying to find the best way to effect a destructor, you're doing too much. If you find you're allocating too much memory, preallocate a pool of curves and then work on their `.points` arrays directly (with the associated `update()` call every time to redefine a curve), but other than that, JS will simply schedule GC when most appropriate given the thread activity and JS engine priority.
