### ISSUE TITLE
Getting started with bezier.js in a browser

### ISSUE THREAD

**Issue by mmm954** [Pomax/bezierjs#126]
Hi, I apologise for this newbie question—I couldn't find any Information in the documentation (probably I have too little experience in coding and githubing for this).
I try to use bezier.js in a browser to draw a curved line and get its lenths but I can't even get a line—just a blank page (I use JS and Safari to test).

Could you please advise if it's possible to draw bezier lines in a browser (by loading bezier.js or other sources) and where I can see an example?

Thank you.

**Comment by vantreeseba** [comment]
You need to use something like webpack to transpile this into a useable browser module.

Currently (if you open the console you should see an error about require) it uses the module loading from node and is not distributed as a single browser loadable file.

**Comment by vantreeseba** [comment]
Actually I'm wrong and can't read.

The bezier.js at the root of the repository is the single file with everything included.

If you use that file in the browser, it should give you something.


https://codepen.io/vantreeseba/pen/dyGQLyO

**Comment by GoldenQubicle** [comment]
Struggled with this as well, thanks for the example. 👍
So turns out it's not as simple as 'Load the toplevel bezier.js' as the readme claims, nor is binding to an element mentioned anywhere.

**Comment by vantreeseba** [comment]
I wouldn't claim this is the right way to use it, I just didn't find the documentation clear either and this is the way I got it showing something.

**Comment by Pomax** [comment]
bezier.js itself has zero drawing code in it, it's a utility function for doing all the maths around Bezier curves. If you want to draw things, you'll have to write that part yourself, but thankfully the Canvas2D API does most of this already. So, an example:

On the HTML side, we have:
```html
...
<script src="bezier.js" defer></script>
...
```
And then let's say you have an index.js:
```js
let canvas = document.createElement('canvas');
canvas.width = canvas.height = 100;
document.body.appen(canvas);

let ctx = canvas.getContext('2d');
let curve = new Bezier(0,0, 0,100, 100,100, 100,0);
let p = curve.points;

ctx.beginShape();
ctx.moteTo(p[0].x, p[0].y);
ctx.bezierCurveto(p[1].x, p[1].y, p[2].x, p[2].y, p[3].x, p[3].y);
ctx.stroke();
```
