### ISSUE TITLE
SVGtoBeziers throws error on a pretty standard SVG Path string

### ISSUE THREAD

**Issue by Vadi** [Pomax/bezierjs#129]
I'm trying to parse a simple SVG Path string. Below is how it would look like:

![image](https://user-images.githubusercontent.com/218148/90307522-8ac87180-def4-11ea-9516-661293c28283.png)

```
<svg width="199" height="101" viewBox="0 0 199 101" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M80 100C108 95.3333 131.4 69 1 1H49L197 100H80Z" stroke="black"/>
</svg>
```
Just took the path string from above SVG, with below code, 

```
const Bezier = require('bezier-js');
Bezier.SVGtoBeziers("M80 100C108 95.3333 131.4 69 1 1H49L197 100H80Z");
```

it throws error:

```
Error: Only new Bezier(point[]) is accepted for 4th and higher order curves
```
I would assume this is pretty standard SVG (pulled out from a Sketch file) and wondering why the library is unable to parse. I see that during the first run `arguments` pased into `Bezier` constructor only had 4 arguments, which was not acceptable.

**Comment by Pomax** [comment]
You may have noticed the actual API documentation doesn't mention this function: don't use it. Or if you do, remember to read the code for it first, because the only thing that function does is convert bezier paths to bezier objects. It won't parse arbitrary SVG.
