### ISSUE TITLE
Small mistake in utils.js could cause bug in 3D

### ISSUE THREAD

**Issue by FlashTang** [Pomax/bezierjs#134]
In utils.js - function -  compute at about line 161
As you can see , dCpts[i].z always "undefined" ,since dCpts[i] = {x..y..}  ,it defines as new object , there is no z
should like so:
dCpts[i] = {x..,y..,z: dCpts[i].z}
 
or 

dCpts[i].x = ...
dCpts[i].y = ...
if ...z !== "undefined" 

P.S. this line shoud dCpts[i].z = .... 
`dCpts[i] = dCpts[i].z + (dCpts[i + 1].z - dCpts[i].z) * t;`

Original code:

```
// higher order curves: use de Casteljau's computation
      var dCpts = JSON.parse(JSON.stringify(points));
      while (dCpts.length > 1) {
        for (var i = 0; i < dCpts.length - 1; i++) {
          dCpts[i] = {
            x: dCpts[i].x + (dCpts[i + 1].x - dCpts[i].x) * t,
            y: dCpts[i].y + (dCpts[i + 1].y - dCpts[i].y) * t
          };
          if (typeof dCpts[i].z !== "undefined") {
            dCpts[i] = dCpts[i].z + (dCpts[i + 1].z - dCpts[i].z) * t;
          }
        }
        dCpts.splice(dCpts.length - 1, 1);
      }
      return dCpts[0];
    }
```

**Comment by Pomax** [comment]
fixed as part of the es6 release, now on npm as v3.0.1
