### ISSUE TITLE
License of Bezier curve algorithm

### ISSUE THREAD

**Issue by canhnht** [Pomax/bezierjs#136]
I'm not sure if this is an irrelevant question, but I'm wondering if all the Bezier curve's algorithms have license.
Is it okay to add it to a commercial application?
Is there anything related to Bezier curve have license that cannot be added to a commercial application?
Thanks in advance.

**Comment by Pomax** [comment]
I would be very surprised if there were, but I'm not a lawyer so I can't definitively tell you that nothing is unlicensed. Someone might have come up with a crazy efficient way to perform multidimensional intersection detection, with a paper published and a software patent on that procedure, but many countries don't recognize software patents, so the real answer here is that even if they do (and certainly none of things in this library do) depending on where you live those licenses might or might not apply.

Having said that, you can't really license maths, even if you can license specific code implementations, so even if Matlab's implementation for Bezier curves is under license, that doesn't stop you from implementing your own maths implementations. No one owns summation, or integrals, or calculus, and no one owns the concept of "implementing mathematical operations".
