### ISSUE TITLE
How to obtain 3D segment points of shape enclosed by curves?

### ISSUE THREAD

**Issue by hydroper** [Pomax/bezierjs#145]
Is it possible to obtain [x, y, z] points of a shape's outline that is described by Bézier curves?

For example, I want the points out of the following green fill:

![Shape](https://user-images.githubusercontent.com/52384977/103460150-d5575880-4cf2-11eb-870c-6a8101394be0.png)

To clarify, I'm looking for a Bezier method like `bezier.to3DPoints()`, which will return a sequence of 3D points closing a polygon.

**Comment by Pomax** [comment]
I don't understand your question. You're showing a 2D shape, with two shades of green. Can you be more descriptive in what the start situation is, what procedure you run through, what that results in, and what you want to measure/obtain from that resultant situation?

**Comment by hydroper** [comment]
I think that what I want would not make sense at all, so I guess I'm closing my issue...
