### ISSUE TITLE
intercepts function doesn't work with perfectly-horizontal intercepting lines

### ISSUE THREAD

**Issue by axefrog** [Pomax/bezierjs#15]
```js
var test_bezier = [0, 1.74, .21, 1.67, .28, 1.32, .28, .86];
var test_line = { p1: { x: -.56, y: .95}, p2: { x: .56, y: .95 } };
var test_curve = new Bezier(test_bezier);
var intersections = test_curve.intersects(test_line);
if(intersections.length === 0) throw new Error('Expected at least one intersection');
```

The test curve and line above definitely intersect. I've checked and rechecked multiple times, including drawing the points (at various scales) onto a canvas. bezier.js fails to return any intersection points.

I've actually got a surfboard shape comprised of a set of bezier curves, and I'm using bezier.js to calculate around 150 slice points along the length of the board, but the intersections returned are very intermittent. I typically assume my code is at fault before assuming a library is at fault, but that test case above seems pretty clear.

**Comment by axefrog** [comment]
Further investigation reveals that the problem is something to do with the fact that my line is a perfectly straight horizontal line. If vary the `y` coordinate on either end of the line by even so much as `0.00000001`, then the intercept is found. It's only when they're equal that the intercept fails.

**Comment by Pomax** [comment]
hm, that sounds like somewhere the y delta being 0 is leading to bad stuff... division by zero perhaps. Good find!

**Comment by axefrog** [comment]
No worries. Great library overall though, so thanks- it's saved me a tonne of time!

**Comment by dom1n1k** [comment]
Vertical lines too.
But it works:
```javascript
var vertical = {
    p1: { x: x, y: 0 },
    p2: { x: x + 1e-10, y: 1 },
};
bezier.intersects(vertical);
```

**Comment by harjis** [comment]
Hi!

First of all great work with the library! Has saved me a ton of time.

The issue I have is an intersection with cubic bezier curves and straight horizontal bezier curve. My code is as follows:
```js
    const r = 150;
    const k = 0.55228;
    const circleArc = [
      { x: r * 2, y: r }, // Intersection point
      { x: r * 2, y: r + k * r },
      { x: r + k * r, y: r * 2 },
      { x: r, y: r * 2 }
    ];
    const straightLine = [
      { x: r, y: r },
      { x: r * 2, y: r }, //Intersection point
      { x: r * 2 + k * r, y: r },
      { x: r * 4, y: r }
    ];
    const circleArcBezier = new Bezier([...circleArc]);
    const straighLineBezier = new Bezier([...straightLine]);

    console.log(circleArcBezier.intersects(straighLineBezier)); // Empty array
```

To my understanding the lines should intersect each other at point ```{ x: r * 2, y: r }```. Also If I change the straight line even 1px the intersection is detected.

![screen shot 2017-06-05 at 10 36 57](https://cloud.githubusercontent.com/assets/2409276/26774868/fbbb941a-49da-11e7-8dc7-2f00db8ce697.png)

I'm not sure if this is the same issue as in https://github.com/Pomax/bezierjs/issues/70 so I commented here.

Thanks again for your awesome work!

**Comment by harjis** [comment]
Oh yeah and this happens in Chrome Version 58.0.3029.110 (64-bit) and Firefox 53.0.3 (64-bit) at least with version 2.2.3

**Comment by Pomax** [comment]
hi @harjis can you please file this as a new issue. Closed issues should remain closed, to keep single issues tied to single PRs.
