### ISSUE TITLE
Monotone bezier interpolation

### ISSUE THREAD

**Issue by Muini** [Pomax/bezierjs#157]
Hi !

First, thank you for the documentation about bezier, i've learned so much about it thanks to you.

I'm using bezier.js for a project to compute and spacial (x & y) interpolation of an object so it's following a path. I'm computing the bezier passing time as `t`. However the bezier result of time is not constant, steps are not equally distant from each other resulting in a movement that accelerate and decelerate even if though time has a constant step.

I've found out about this on wikipedia : [Monotone cubic interpolation](https://en.wikipedia.org/wiki/Monotone_cubic_interpolation)

I'm wondering if it would solve it and if it is implemented ?

Thanks.

**Comment by Muini** [comment]
I think [this is the section I was looking for](https://pomax.github.io/bezierinfo/#tracing)

**Comment by Pomax** [comment]
yeah, there's no symbolic solution (technically there is one for quadratic curves, but the maths is _ridiculous_ rather than just "impossible") so numerical solutions are pretty much the only way to do this, with the choice in lookup and point interpolation function determining accuracy.
