### ISSUE TITLE
Feature Suggestion: Infinite line for intersect?

### ISSUE THREAD

**Issue by jrj2211** [Pomax/bezierjs#159]
Is it possible to get an intersection along an infinite line?

```
    const line = {
      p1: {x, y: Number.NEGATIVE_INFINITY},
      p2: {x, y: Number.POSITIVE_INFINITY}
    }
    const intersections = bezier.intersects(line);
```

When changing from using INFINITY to a smaller integer it begins working. I've found the cut off somewhere between 10000000000 and 19999999999. In my application I can guarantee I wouldn't ever have a number larger than max int 32 so I'm using that but using a defined constant such as Infinity would be nicer.

In my use case I'm only checking a vertical line, but I imagine other people needing to check for intersections along an infinite line in any orientation. I'd like to propose a feature request where intersects can also just take a slope instead of two points, and calculate any intersections along an infinite line. 

```
bezier.intersects({slope: {x: 0, y: 1}); // Vertical line
bezier.intersects({slope: {x: 1, y: 0}); // Horizontal line
bezier.intersects({slope: {x: 1, y: 1}); // 45 degree line
bezier.intersects({slope: {x: 3, y: 4}); // 53.13 degree line (handle unnormalized coordinates)
```

**Comment by Pomax** [comment]
I'm not sure anyone actually needs to: an infinite line is just an axis, rotated. So rotate your curve coordinates by the opposite degree so that it's axis-aligned, and now you just check where the intersections with the axis are. Infinite lines are just rotated coordinate systems.
