### ISSUE TITLE
May I help improve the docs website

### ISSUE THREAD

**Issue by fengzilong** [Pomax/bezierjs#162]
Hey, this is an awesome library bro!

It provides all I need about bezier, definitely you paid much work on this project ( it had been actively maintained for years ❤️ ), so I'm passionate about helping such a great project to improve its docs website

Here are some points I came up with currently:

- Add installation, basic usage guide
- Put api into reference section, and add TOC for APIs (for quick navigation)
- Display code and preview side-by-side which is more intuitive
- Add syntax highlighting and copy button for code( preview [theme](https://www.rem.rocks/hi-there) here which is used in my blog, you can choose [other themes](https://vscodethemes.com/) here if you prefer )
- Styling tips ( to make them striking )
- Add playground to live edit code, which can also be used to reproduce bug when reporting issues
- Apply for `bezier.js.org` domain, it's easier to remember
- Add your sponsor link in website( Hope it'll bring some sponsors for you )
- More...

If I have extra time, I can do following

- Translate into Chinese in another PR
- Add light and dark mode( anyway it's very popular nowadays )
- Add GitHub issue template for better issue reporting
- More...

FYI: I'll use [`vite`](https://vitejs.dev/) or [`webpack`](https://webpack.js.org/)( as dev server ), [`react`](https://reactjs.org/)( to write components ), I hope you don't mind me using them

What do you think about it? Can I start my work on this

**Comment by Pomax** [comment]
This isn't a react library, so creating a vite/react site for it makes very little sense. In fact, the whole point is that it's a plain JS library and so will work with _anything_.

That said, I'm not particularly interested in a new website for it at the moment: as just a utility that people seem to be able to find just fine, the current page, hosted as a github page, feels like it's doing its job well enough.

But thank you for your enthusiasm.
