### ISSUE TITLE
 Some points of the outline method are not accurate

### ISSUE THREAD

**Issue by RodionNikolaev** [Pomax/bezierjs#166]
I take your "outline" example with the same coordinates of points and with the same "d" parameter.
Most result points are correct, but, some points have the significant offsets

<img width="400" src="https://user-images.githubusercontent.com/10497662/147405673-3652c178-d97e-49b7-b3f9-1a7f725ff681.png">

**Comment by Pomax** [comment]
Can you explain what I should be noticing here? As far as I can tell, the outlines are correct (the code you're using does not "join up" the offsets, because there are too many ways to join up disjoints, so that's entirely up to what you want things to look like)

**Comment by RodionNikolaev** [comment]
Thank you for your answer. 
I just hoped to get the points located on the red lines to get the correct outline.

**Comment by Pomax** [comment]
Which you can, because the output of `curve.outline(...)` is an array of curves, so I still don't understand the question? Your issue is titled "some points of the outline method are not accurate", so _which_ points are you seeing that aren't what they should be?

**Comment by sambauers** [comment]
I think @RodionNikolaev is saying that the green dots are not positioned on the outline. It looks like those green dots are a mix of positional points and control points, so they may just be misinterpreting their output.

**Comment by Pomax** [comment]
Ah, that's possible. @RodionNikolaev if that's the case, all the points you're seeing that are "not on the curve" are the Bezier control points. I've added some color and lines to your picture hopefully make that clear:

![image](https://github.com/Pomax/bezierjs/assets/177243/11d710da-0b76-466c-90a8-201aeca96843)
