### ISSUE TITLE
new Bezier() use of `arguments` is broken, and unrelatedly, slows down Chrome

### ISSUE THREAD

**Issue by idupree** [Pomax/bezierjs#17]
(thank you for your great library and giving me a chance to improve it! sorry for the dire-sounding headline on a very minor issue)

Passing multiple arguments doesn't work (as compared to an array of arguments, which does) because line 500-507 iterates coords rather than args.  I can fix this with a few lines of changes, or remove it with something like
```
-    var args = (coords && coords.forEach ? coords : arguments);
+    var args = coords;
```
Any preference which? I'm happy to send a pull request.

I noticed this because Chrome's profiler noted that it doesn't know how to optimize array-like uses of `arguments` (see https://code.google.com/p/v8/issues/detail?id=3037 ), which keeps it from optimizing the entire function.  Fixing this changed it from the slowest thing in my profile to something more reasonable.  The workaround is apparently to iterate through arguments like `var args = []; for(var i = 0; i !== arguments.length; i++) { args.push(arguments[i]); }` (as suggested in https://github.com/bevry/taskgroup/issues/12#issue-23512231 ).  Less importantly, I'd probably check for multiple arguments by checking `arguments.length` rather than `coords && coords.forEach`.

**Comment by Pomax** [comment]
Before we go down that route, can you explain what you mean with "doesn't work"? [this line](https://github.com/Pomax/bezierjs/blob/gh-pages/bezier.js#L499) ensures that the following calls all work, which you can verify by pulling up a dev console on http://pomax.github.io/bezierjs and running them in the console:

- new Bezier(1,2, 3,4, 5,6)
- the same but for 4 pairs
- new Bezier(1,2,3, 4 5,6, 7,8,9)
- the same but for 4 pairs
- new Bezier([{x:1,y:2},{x:3,y:4},{x:5,y:6}])
- the same but with 4 pairs, z-coordinates, and both

**Comment by idupree** [comment]
I knew I should have given an example! Sorry. `new Bezier({x:1,y:2},{x:3,y:4},{x:5,y:6})`

**Comment by Pomax** [comment]
You're right, that won't work: but if you put them in an array and pass that in, it'll work fine.

**Comment by idupree** [comment]
We can easily make it work. Putting it in an array works fine too, of course (which is what I did in my code).

**Comment by Pomax** [comment]
The fix here will be to replace this:
```
    if(typeof args[0] === "object") {
      args = [];
      for(var i=0; i<coords.length; i++) {
        ['x','y','z'].forEach(function(d) {
          if(typeof coords[i][d] !== "undefined") {
            args.push(coords[i][d]);
          }
        });
      }
    }
```
with this
```
    if(typeof args[0] === "object") {
      newargs = [];
      for(var i=0; i<args.length; i++) {
        ['x','y','z'].forEach(function(d) {
          if(typeof coords[i][d] !== "undefined") {
            newargs .push(args[i][d]);
          }
        });
      }
      args = newargs;
    }
```

**Comment by idupree** [comment]
Yep, that looks right!  Probably `var newargs =` instead of `newargs =`.

**Comment by idupree** [comment]
For the other part, the odd Chrome performance issue, do you think the workaround makes sense?

**Comment by Pomax** [comment]
sort of. Might as well just do a straight up array cast, though.
```
var args = ... Array.prototype.slice.call( arguments )
```

**Comment by idupree** [comment]
That's what I thought too, but apparently even that isn't optimized well in Chrome (I read that in a bug report and just tested in my Chromium to double check).

**Comment by idupree** [comment]
I'd love to be missing something, though, so let me know if you find something different. I'm checking whether it's optimized well by running the profiler in Chromium and looking for the yellow exclamation-mark warning sign next to Bezier in the "Heavy (bottom up)" profile. Mouse over the warning sign to see the message describing the warning.

**Comment by Pomax** [comment]
I've pushed the update, so you can check what Chrome thinks of that.

**Comment by idupree** [comment]
I'm still seeing a warning message in the profiler.

**Comment by idupree** [comment]
If you want to see where I'm testing, it's at https://github.com/idupree/trainworldii that you can compile with `tsc script.ts` and then open index.html in a browser (first edit bezier.js to be the version you want it to be).  If that's too complicated I can make it easier to test.

**Comment by idupree** [comment]
On further investigation, even with the difference in ⚠ vs not, it's now taking about the same amount of time for me either way in the profile.  I wonder if I missed something before.  I am satisfied to tentatively close this ticket unless/until anyone can measure a large time difference in the future.

**Comment by Pomax** [comment]
in that case let's close this, until such time someone else run into it.

**Comment by idupree** [comment]
Thanks!
