### ISSUE TITLE
Custom menu is overlapped by normal menu in "Cortex Prime" game system

### ISSUE THREAD

**Issue by ashleytowner** [Pomax/bezierjs#181]
Due to the added dice button on the left here, the default UI overlaps the custom UI elements in the Cortex Prime system.
![image](https://user-images.githubusercontent.com/13824257/166458549-ae2dc862-7e69-4300-896d-13650c250ca0.png)

**Comment by Pomax** [comment]
I'm pretty sure you filed this on the wrong repo? This library does not have any UI code, it's just a maths library.
