### ISSUE TITLE
Curve intersections often give multiple almost identical results

### ISSUE THREAD

**Issue by mblinsitu** [Pomax/bezierjs#184]
When intersecting two Bezier segments, I often get 2 or 3 intersections that are very close to each other instead of a single one. For example:
```js
		let b1 = new Bezier(100, 100, 200, 150, 400, 600, 500, 300)
		let b2 = new Bezier(100, 500, 150, 550, 400, 100, 500, 100)
		b1.intersects(b2)
		// ["0.466/0.50723", "0.46608/0.50723", "0.46615/0.50723"]
```

Is this a bug or a feature? I tried to play with the `curveIntersectionThreshold` parameter but it didn't help.

Thanks!

**Comment by Pomax** [comment]
This is unfortunately a consequence of the "divide and conquer" algorithm. At the scale of "this bounding box constitutes a little less than a pixel" we get one or more adjacent-but-not-overlapping, bounding boxes on one curve, overlapping a similar set of one or more bounding boxes on the other curve. So you can end up with quite a few intersection points that are nearly identical.
