### ISSUE TITLE
_lut caching doesn't work: steps is off by one

### ISSUE THREAD

**Issue by justvanrossum** [Pomax/bezierjs#190]
Because of `steps++` on line 248, the `if (this._lut.length === steps)` condition on line 243 always fails, as the lut will get a length of `steps + 1`:

https://github.com/Pomax/bezierjs/blob/d19695f3cc3ce383cf38ce4643f467deca7edb92/src/bezier.js#L240-L257

Perhaps move `steps++` to before the condition?

Or change the condition to `if (this._lut.length === steps + 1)`?

 I can make a PR if you want.

**Comment by Pomax** [comment]
Gah! good catch, let's make the check `if (this._lut.length === steps + 1)`.

**Comment by Pomax** [comment]
v6.1.1 published to npm

**Comment by justvanrossum** [comment]
> v6.1.1 published to npm

Thanks!

I think the dist/ folder needs updating, too. I wouldn't know how to conribute that, though.

**Comment by Pomax** [comment]
ah, forgot to run `npm test` =_=

**Comment by Pomax** [comment]
6.1.2 published >_>
