### ISSUE TITLE
add "project" for projecting a point onto the curve

### ISSUE THREAD

**Issue by Pomax** [Pomax/bezierjs#20]

**Comment by Pomax** [comment]
added in v1.5.0

**Comment by danmarshall** [comment]
Hi there, I'm seeing a bug on lib/bezier.js line 193:
     LUT.forEach((p,idx) => {
JavaScript doesn't like the lambda ;-)

**Comment by Pomax** [comment]
That's the node.js version (for the browser, use the root `bezier.js`). Current versions of Node.js [should](https://nodejs.org/en/docs/es6) support arrow functions, how are you using it?

**Comment by danmarshall** [comment]
I clicked the "Try it out" link on the npmjs.com site which runs Tonic in the browser
https://tonicdev.com/npm/bezier-js

**Comment by Pomax** [comment]
Yeah, that will most certainly fail. I have no idea why npm adds that link (there's nothing in the package.json to indicate it'll work in the browser by using the main entry point).
