### ISSUE TITLE
The intersection of two identical curves

### ISSUE THREAD

**Issue by ArtOfOmission** [Pomax/bezierjs#204]
```
  var cv1 = new Bezier(48, 84, 100, 187, 166, 37);
  var cv2 = new Bezier(48, 84, 100, 187, 166, 37);
  
  var icts = cv1.intersects(cv2);
  console.log(icts.length);
```
These are the same two curves(or one is part of the another), the result has more than 700 intersections.
In my project, there should be no intersection, I don't know how to handle it.

**Comment by Pomax** [comment]
> there should be no intersection

There should be _infinitely many intersections_ because literally every point on the curve overlaps the other curve. You catch this by first checking whether the coordinates are the exact same, before running an intersection call.

**Comment by ArtOfOmission** [comment]
I found a piece of literature that answered my question
[https://www.researchgate.net/publication/283076594_The_Study_of_Coincidence_or_Partial_Coincidence_Condition_for_Two_Rational_Cubic_Bezier_Curves](url)
