### ISSUE TITLE
Ability to get and estimate the centerline of a list of 3D points

### ISSUE THREAD

**Issue by omaramen99** [Pomax/bezierjs#206]
Can I use this library to get the center of set of 3D points as a curve or straight line?
similar to the following sample image
![sample](https://github.com/Pomax/bezierjs/assets/56793975/67645924-b32a-4373-9c4c-1073924a7ca3)

**Comment by Pomax** [comment]
You'd need a polynomial regression library for that I'm afraid.

**Comment by omaramen99** [comment]
Thank you, I recommend this Package [[polynomial-regression-js](https://www.npmjs.com/package/@rainij/polynomial-regression-js?activeTab=readme)] for any one have interest in this issue.

**Comment by Pomax** [comment]
I've updated your comment just to remove the endorsement, because there are plenty of choices, and this issue tracker is not an endorsement platform =D
