### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by personalizedrefrigerator** [Pomax/bezierjs#212]
Hi,

While the README states that `bezierjs` is licensed under the MIT, there is no `LICENSE` file.

The MIT license states, in part,
```
The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.
```

Including a copy of the MIT license (and thus a copyright notice) would make it much easier to give proper attribution to this library.

Thank you for this amazing library!

**Comment by Pomax** [comment]
added in https://github.com/Pomax/bezierjs/commit/4e767299184ab4079dc8d7c970020103db14f431
