### ISSUE TITLE
How to Find Y-Coordinate for a Given X-Coordinate on a Bezier Curve

### ISSUE THREAD

**Issue by Typogram** [Pomax/bezierjs#216]
Hello, I'm currently working on a project where I need to calculate the y-coordinate of a point on a Bezier curve given an x-coordinate. I understand that Bezier.js provides functionalities such as `get(t)` to get the point on the curve for a given `t` parameter, but I'm wondering if it is possible to find the y-coordinate for a specific x-coordinate? Maybe it is hard because there could potentially be two or more y coordinate.

I would greatly appreciate any insights, advice, or references to documentation or examples that could assist me in implementing a solution for this problem.

**Comment by Pomax** [comment]
https://pomax.github.io/bezierinfo/#yforx =)

**Comment by Typogram** [comment]
Wow thanks! This is super helpful! I have ran into your comments in various github repo about fonts, it is great to dive into your work!

**Comment by Pomax** [comment]
always great to hear!
