### ISSUE TITLE
Get the base bezier class

### ISSUE THREAD

**Issue by changjianli** [Pomax/bezierjs#32]
Hi,

Thanks a lot for your excellent work, I want to know that can I get the base bezier class in C++ format? I remembered that I can get that code some days ago, but now I can not find that code. Can you share me a copy?

Thanks a lot.

Best,
Eric

**Comment by Pomax** [comment]
Hmm, I haven't written any C++ in over ten years, and this repo never had any .cpp/h files, so I'm afraid you're asking the wrong person.

**Comment by changjianli** [comment]
I did read a similar page which can view source under every example, then it was written by c++. Maybe there is something wrong with that.

Anyway, thanks a lot for you reply!
