### ISSUE TITLE
Type returned by split()

### ISSUE THREAD

**Issue by danmarshall** [Pomax/bezierjs#36]
Hi @Pomax ,

I'm trying to understand the type of object returned by the *split* method of the *Bezier* class.
It seems that it can return either:
* a Bezier, 
* a "subsplit" object with a *left* Bezier and a *right* Bezier.

I'm guessing that the subsplit might only be for internal use by split itself?

**Comment by Pomax** [comment]
if called as `split(t)` you'll get an object with a left/right pair, because you've split the curve into two curves. If called as `split(t1,t2)` you'll get the Bezier subcurve between those two `t` values.

**Comment by danmarshall** [comment]
Thanks Mike!

**Comment by xxao** [comment]
It might be a good idea to have two functions instead of one:
split(t)
slice(t1 ,t2)

**Comment by Pomax** [comment]
I see no real reason for that, if you write the code, you know how many arguments you passed in, which directly results in knowing how many curves you should be expecting back.
