### ISSUE TITLE
Circle intersection

### ISSUE THREAD

**Issue by danmarshall** [Pomax/bezierjs#39]
Hi Mike,
What is a good strategy for detecting intersection of a Bezier curve and a circle? Would you recommend using 4 curves, each approximating a quarter circle?

**Comment by Pomax** [comment]
Given the high number of intersections, I'd probably recommend doing bounding box iterations, much like for regular curve/curve intersection testing. A circle and a cubic curve can have up to six intersections, so iteratively splitting the curve into subcurves and the circle into arcs, then weeding out parts without bounding box overlaps and redividing the parts that do, is a cheap way to find all intersections, reasonably fast, and reasonably accurately.
