### ISSUE TITLE
Uncaught TypeError: t.split is not a function

### ISSUE THREAD

**Issue by lgcc** [Pomax/bezierjs#41]
```javascript
var curve = new Bezier(330,592,330,557,315,522,315,485);
curve.offset(20);  // it causes TypeError
```
I found it was generated while calling t.split within .reduce function of curve.

**Comment by Pomax** [comment]
that is very curious - thanks for reporting it, I'll have a look at why this happens.

**Comment by Pomax** [comment]
Turns out this is actually happening in the constructor itself, `var curve = new Bezier(330,592,330,557,315,522,315,485);`

**Comment by Pomax** [comment]
it looks like the `inflections` function got overwritten at some point to only test cubic inflections... no idea why, but restoring that to cover the other cases again now.

**Comment by Pomax** [comment]
Interestingly that's only part of the problem. Solving for inflections, there is a super fascination split result:
```
{ left:
   { [String: '[330/592, 330/592, 330/592, 330/592]']
     _3d: false,
     order: 3,
     points: [ [Object], [Object], [Object], [Object] ],
     dims: [ 'x', 'y' ],
     dimlen: 2,
     _linear: true,
     _t1: 0,
     _t2: 0,
     dpoints: [ [Object], [Object], [Object] ],
     clockwise: false },
  right:
   { [String: '[330/592, 330/557, 315/522, 315/485]']
     _3d: false,
     order: 3,
     points: [ [Object], [Object], [Object], [Object] ],
     dims: [ 'x', 'y' ],
     dimlen: 2,
     _linear: false,
     _t1: 0,
     _t2: 1,
     dpoints: [ [Object], [Object], [Object] ],
     clockwise: true },
  span:
   [ { x: 330, y: 592 },
     { x: 330, y: 557 },
     { x: 315, y: 522 },
     { x: 315, y: 485 },
     { x: 330, y: 592 },
     { x: 330, y: 557 },
     { x: 315, y: 522 },
     { x: 330, y: 592 },
     { x: 330, y: 557 },
     { x: 330, y: 592 } ],
  _t1: -0,
  _t2: 0 }
```
I can't remember the last time I saw `-0` in JavaScript...

**Comment by Pomax** [comment]
Turns out the error came from `extrema()`, which would happily return a list like `[-0, 0, 0.5, 1]`, which would then lead to the code forming segments between each of those `t` values, which would lead to it trying to form a segment by calling `thing.split(-0,0)` which broke **all** the things.

I've extended the tests to explicitly check the result of `extrema()` using your curve parameters to prevent any code changes in the future screwing this back up =D
