### ISSUE TITLE
register in Bower

### ISSUE THREAD

**Issue by eagor** [Pomax/bezierjs#42]
we all love npm, but having `bower install bezierjs` would be as good.

**Comment by Pomax** [comment]
I disagree, for many reasons explained by other people in good posts on medium and personal blogs (versioning gets completely ignored, projects download in their entirety, then prune "ignore" files, no deduplication, unnecessary build system complexity, the list goes on), but the most concise form is "if you have JS dependencies, use one manager for them", and today the most mature and reliably available manager is `npm`.
