### ISSUE TITLE
Inverse of .compute?

### ISSUE THREAD

**Issue by gavinwahl** [Pomax/bezierjs#49]
Is there a way, given a point on the curve, to get the t value for that point? For non-degenerate quadratic curves it should be unique.

**Comment by danmarshall** [comment]
I think this is a duplicate issue of https://github.com/Pomax/bezierjs/issues/25

**Comment by gavinwahl** [comment]
Yes, thank you

**Comment by Pomax** [comment]
Yup, tracking that already, although the problem isn't so much that it's easy for some classes of curve, but that the function need to cover all classes: degenerate as well as non-degenerate, and quadratic and cubic at the very least. If you look at http://pomax.github.io/bezierinfo/#canonical the number of cubics with unique solutions actually well outweight the number of cubics that can yield multiple `t` values, but implementing a full `getTForPoint` equivalent is still a lot of different algorithms to seemingly do just one thing.
