### ISSUE TITLE
[question] what is ._t1 ._t2 props' purpose?

### ISSUE THREAD

**Issue by louisremi** [Pomax/bezierjs#52]
Those props are [initialized in the constructor](https://github.com/Pomax/bezierjs/blob/gh-pages/lib/bezier.js#L97) a used in a few places throughout the code. I haven't been able to figure out what is their purpose.

Could you explain this to me?
Thank you in advance :-)

**Comment by Pomax** [comment]
as I recall they are "original `t` intervals" for curves that come out of `split` and `reduce`, so that there is a way to determine where, on the original curve, the sections-of-curve came from.

**Comment by louisremi** [comment]
Thanks! That makes sense.
