### ISSUE TITLE
[suggestion] Make 0xFFFFFFFFFFFFFFFF a constant and use it consistently

### ISSUE THREAD

**Issue by louisremi** [Pomax/bezierjs#53]
The value 0xFFFFFFFFFFFFFFFF is used in utils.getminmax but not in utils.findbbox. I believe the same value should be used in both cases.

Am I correct? Should I send a PR?

**Comment by Pomax** [comment]
Given that the max int value that JS can represent is 9007199254740991 (0x1FFFFFFFFFFFFF), that value is most certainly incorrect.

**Comment by louisremi** [comment]
Ok, so should the code use 0x1FFFFFFFFFFFFF instead of 0xFFFFFFFFFFFFFFFF and 99999999?
I believe I've also seen bbox algorithms in js using +Infinity and -Infinity. This should work well.

**Comment by Pomax** [comment]
I don't really like `Infinity` for the fact that it's not correct (`Infinity === Infinity` is true, which is absolute nonsense, mathmatically) so I'd much rather use `Number.MAX_SAFE_INTEGER` and `Number.MIN_SAFE_INTEGER`

**Comment by louisremi** [comment]
Alright, let me know if you want me to do that PR or if you find it quicker to do it yourself.

**Comment by Pomax** [comment]
PRs are always quicker than me adding it in unless I'm in a period of active maintenance, which for bezier.js I'm not =)
