### ISSUE TITLE
Suggestion: Make PolyBezier constructor public

### ISSUE THREAD

**Issue by louisremi** [Pomax/bezierjs#57]
I suggest exposing it either as Bezier.Poly or Bezier.PolyBezier (I vote for the conciseness of Bezier.Poly).

Should you agree, I'll gladly send a PR :-)

**Comment by Pomax** [comment]
Making it a publically accessible object will also require documenting the API for it in the `index.html`, because no code should get added to the public API (even by just exposing preexisting code) without documentation that explains how to use it =)

What would the main utility be? having linked control vertices?

**Comment by louisremi** [comment]
To be honest I don't have a particular utility. I just noticed you took the time to add a few methods to that constructor, but I noticed the only way to use that code is to call Bezier#outline first. I figured it would be more useful if it was public.

BTW: PolyBezier#toString seems wrong. It should map utils.pointsToString on this.curves

**Comment by Pomax** [comment]
It's mostly a stub object used exclusively as a wrapper for what comes out of the Bezier.outline function. If there is no particular use-case, I'd rather keep this thing private as it does nothing other than act as an array with a few trivial functions tacked on. It doesn't do any validation, control point linking, on-curve point linking, etc. etc. so it's *not* a PolyBezier in the true sense. It's just a fancy array.

As for `toString`, yeah that looks like a copy-paste error. That's probably worth fixing, but then in its own issue.

**Comment by louisremi** [comment]
Alright!

**Comment by HavardNJ** [comment]
Kind of want this too, if it did what it says on the tin. Need to wrap my own now I guess.
