### ISSUE TITLE
It seems the folder test/manual is missing in this repo

### ISSUE THREAD

**Issue by louisremi** [Pomax/bezierjs#58]
This folder is referenced in package.json:
```js
"scripts": {
    "test": "npm run build && node test",
    "test:manual": "http-server test/manual",
    "build": "..."
}
```
But it isn't present in the repo. Have you renamed it to "autodraw", or simply forgotten?

**Comment by Pomax** [comment]
Hm, I think it was in preparation for a manual test dir that never ended up getting made.

**Comment by louisremi** [comment]
Alright. May I suggest removing that line and also moving bezierjs/test.js to bezierjs/test/test.js?
I plan on adding a second test file for the FP API, and want to avoid having too many files in the root directory.

**Comment by Pomax** [comment]
sure - if you PR it I'll happily merge that in

**Comment by louisremi** [comment]
There you go: https://github.com/Pomax/bezierjs/pull/60

**Comment by Pomax** [comment]
aaaand landed.
