### ISSUE TITLE
Remove normalization from Utils.angle as it's effectively a noop

### ISSUE THREAD

**Issue by jorgelgm** [Pomax/bezierjs#66]
In function utils.angle, vectors  d1 and d2 should not be normalised between dot and cross product computation. Both products must be calculated either with normalised or non-normalised vectors so atan2 returns the right angle value

**Comment by Pomax** [comment]
No it doesn't... is there an actual bug you found? Because this should work perfectly fine, and the following test code works exactly as it should, finding the correct angle `a` at every iteration:
```
cos = Math.cos; sin = Math.sin; tau = Math.PI *2;
for (var a = 0; a<Math.PI*2; a+=0.1) {
  v1 = {x: cos(a), y: sin(a) };
  v2 = {x: cos(2*a), y: sin(2*a) };
  r = utils.angle({x:0,y:0}, v1, v2);
  // difference between v1 and v2 should be a
  console.log(Math.abs(a - (r+tau)%tau) < 0.00001);
}
```
This gives me `true` for every iteration. 63 times on `a+=0.1`, 629 times on `a+=0.01`.

**Comment by jorgelgm** [comment]
Your code does not show the problem because you are using unit vectors, so it does not really matter if you normalise or not.

Try the same code using lengths > 1. (the angle is the same no matter vectors length).
```
cos = Math.cos; sin = Math.sin; tau = Math.PI *2;
var l1 = 2, l2 = 1;
for (var a = 0; a<Math.PI*2; a+=0.1) {
  v1 = {x: l1*cos(a), y: l1*sin(a) };
  v2 = {x: l2*cos(2*a), y: l2*sin(2*a) };
  r = utils.angle({x:0,y:0}, v1, v2);
  // difference between v1 and v2 should be a
  console.log(Math.abs(a - (r+tau)%tau) < 0.00001);
}
```

I suggest to remove the normalisation because there is no need for using unit vectors.

**Comment by Pomax** [comment]
updated the issue title, will be removing them later today and spinning a new release.

**Comment by jorgelgm** [comment]
Perfect.

However this is a bug, not a noop. If you use lengths > 1 your code will throw only 1 true and false for the rest.

Function should be modified as follows:
angle: function(o,v1,v2) {
      var dx1 = v1.x - o.x,
          dy1 = v1.y - o.y,
          dx2 = v2.x - o.x,
          dy2 = v2.y - o.y,
          //cross = dx1*dy2 - dy1*dx2,
          cross, // do not compute yet. This is bug
          m1 = sqrt(dx1*dx1+dy1*dy1),
          m2 = sqrt(dx2*dx2+dy2*dy2),
          dot;

      // Now you normalize (or not). This is noop
dx1/=m1; dy1/=m1; dx2/=m2; dy2/=m2;
      
      // Now compute dot and cross
       dot = dx1*dx2 + dy1*dy2;
      cross = dx1*dy2 - dy1*dx2, // this is bug fix
      return atan2(cross, dot);
    },


If for any reason you prefer using unit vectors as atan2 input you should normalize them before calculating cross and dot products, not in between.

**Comment by Pomax** [comment]
noted, thanks for the explanation.

**Comment by Pomax** [comment]
normalization removed and v2.2.2 pushed/published
