### ISSUE TITLE
Suggestion: simplify and generalize utils.angle

### ISSUE THREAD

**Issue by louisremi** [Pomax/bezierjs#68]
In our app we've written a small utility that calculates the angle between two lines
```js
export function lla(l1p1, l1p2, l2p1, l2p2) {
  let angle1 = Math.atan2(l1p1.y - l1p2.y, l1p1.x - l1p2.x);
  let angle2 = Math.atan2(l2p1.y - l2p2.y, l2p1.x - l2p2.x);
  return angle1 - angle2;
}
```
This function is rather simple and can also be used to calculate an angle formed by three points: `const angle = lla(A,B,B,C);`. I suggest replacing your implementation of angle by this implementation. I'm ready to open a PR and change code that uses this method if you think this could be useful.

Thank you in advance.

**Comment by Pomax** [comment]
`angle` got simplified in v2.2.2, so the only benefit would be "angle between three points". As a bezier library, what goes in utils is mostly based on "does the library itself need it", rather than "is it useful on its own", because the latter shouldn't be in the bezier-specific utils file =)

**Comment by louisremi** [comment]
Sure, I'll do that as soon as jsperf.com is back online :-)
https://github.com/jsperf/jsperf.com/issues/289

**Comment by Pomax** [comment]
that is not happening ever again. jsperf is down because it could not prevent itself from getting hammered. But you don't need jsperf, writing your own timer in node/browser is pretty easy

**Comment by louisremi** [comment]
Ok, so I tested your updated implementation vs. the one I was suggesting: https://esbench.com/bench/5857b9b0d5686f990078bb32
My tests show that both implementations run equally fast in Firefox, and that the *double atan2* implementation runs 4 times slower in Chrome (Firefox seems 10x faster on this micro-bench). So I'd say let's stick with your implementation.
