### ISSUE TITLE
sort usage

### ISSUE THREAD

**Issue by NaridaL** [Pomax/bezierjs#75]
Minor issue which isn't affecting me but I stumbled across it. You're using .sort() in a couple of places https://github.com/Pomax/bezierjs/search?utf8=%E2%9C%93&q=sort&type= ; you need to pass a comparator, otherwise it does a string based search and e.g. "10" < "2".

https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/sort?v=example

**Comment by Pomax** [comment]
nicely caught.
