### ISSUE TITLE
getCubicRoots() fails when d gets very close to zero

### ISSUE THREAD

**Issue by isonno** [Pomax/bezierjs#85]
The section of code near the top of `getCubicRoots` doesn't check for cases where the combination of coordinates passed in results in `d === 0.0`.  Specifically, the code:
```
  var d = (-pa + 3*pb - 3*pc + pd),
  a = (3*pa - 6*pb + 3*pc) / d,
  b = (-3*pa + 3*pb) / d,
  c = pa / d;
```
results in it failing to find a root when one exists. An example I found is:
```
r = getCubicRoots(12.634216308593750, 1.1288452148437500, -7.9606323242187500, -14.634216308593750)
```
This returns no roots when one obviously exists. ~~As a work around, I've added `if (d == 0.0) d=1` (i.e, ignore the cubic term and solve the quadratic), this returns a reasonable approximation, but I'm not sure if there isn't a more mathematically correct way to address this.~~ See proper fix in comment below.

**Comment by isonno** [comment]
Actually, the correct fix is to just solve the quadratic equation of the cubic term is zero. So the code should read:
```
  var d = (-pa + 3*pb - 3*pc + pd),
  a = (3*pa - 6*pb + 3*pc),
  b = (-3*pa + 3*pb),
  c = pa;
  
  if (d == 0.0)	// Cubic term is zero, so we're really solving a quadratic
  {
    var roots = [(-b + Math.sqrt(b*b - 4*a*c)) / (2*a),
                 (-b - Math.sqrt(b*b - 4*a*c)) / (2*a)];
    return roots.filter(accept);
  }
  
  a /= d;
  b /= d;
  c /= d;
```

**Comment by Pomax** [comment]
Hm, it would make sense to write this in terms of preexisting code, since there's already code in place to evaluate quadratic roots and linear zero-intercepts - while that might require pulling that code out into their own named functions in utils.js [near the `roots()` function](https://github.com/Pomax/bezierjs/blob/gh-pages/lib/utils.js#L312), that would lead to a clearer kind of solution:
```
if (d === 0) {
  return (a === 0) ? utils.lli(...) : utils.qroots(...);
}
...
```

(don't use `==` in JS unless you really know what you're doing and you're *relying* on automatic type-conversion)

**Comment by isonno** [comment]
So, this report should be changed to the cubic root finding fails when `d` is _close_ to zero.  For example, calling this with:
```
getCubicRoots(10.178948735699578, -5.161518874781223, -17.280818031912872, -26.178948735699464)
```
fails, even though there really is a root at 0.2325323987013986. The small value of `d` (-4.092726157978177e-12), causes the subsequent calculations to oscillate wildly off the mark.

The solution is to add the line:
```
  if (Math.abs(d) < 1.0e-6)	d = 0.0;
```
after `d` is initially computed.

**Comment by Pomax** [comment]
There is a special function called `approximately` in the Utils class that is intended for that.

**Comment by Pomax** [comment]
fixed (omg so belatedly...) in https://github.com/Pomax/bezierjs/commit/ed7ea69a5ebe7abc50fff108109af5a86ae246f6

**Comment by jakub-trzebiatowski** [comment]
It took me really long to realize that _d_ is [conventional](https://en.wikipedia.org/wiki/Cubic_equation) _a_, _a_ is conventional _b_, _b_ is conventional _c_ and _c_ is conventional _d_...
