### ISSUE TITLE
LUT cache never reached

### ISSUE THREAD

**Issue by xxao** [Pomax/bezierjs#86]
I think there is a wrong check for LUT cache.
if (this._lut.length === steps)
should be
if (this._lut.length === steps+1)
since the filling loop is from t=0 to t<=steps. Therefore the final number of items in LUT is steps+1

https://github.com/Pomax/bezierjs/blob/0845f082c2a00f0310ddf8800bc07b766b79eb04/lib/bezier.js#L222

**Comment by Pomax** [comment]
excellent point, let me update that and push a new release.

**Comment by Pomax** [comment]
v2.2.8 published.
