### ISSUE TITLE
accept is not defined

### ISSUE THREAD

**Issue by AlcaDesign** [Pomax/bezierjs#87]
```javascript
Uncaught ReferenceError: accept is not defined
    at Object.roots (bezier.js:1)
    at lineIntersects (bezier.js:1)
    at l.intersects (bezier.js:1)
```

How to replicate:

This will throw an error:

```javascript
let b = new Bezier(
	{ x: 0.086, y: -0.041 },
	{ x: 0.080, y:  0.011 },
	{ x: 0.077, y:  0.064 },
	{ x: 0.077, y:  0.117 }
);

b.intersects({ p1: { x: 0.5, y: -1 }, p2: { x: 0.5, y: 1 } });
```

If I modify the second handle, it's now fine:

```javascript
let b = new Bezier(
	{ x: 0.086, y: -0.041 },
	{ x: 0.080, y:  0.011 },
	{ x: 0.070, y:  0.064 },
	{ x: 0.077, y:  0.117 }
);

b.intersects({ p1: { x: 0.5, y: -1 }, p2: { x: 0.5, y: 1 } });
```

There is definition of `accept` in the library. If I write my own `accept` in the global space, it will use it. It's also not being minified to a single character variable so even the minifer knows that it's not anywhere to be found.

https://github.com/Pomax/bezierjs/blob/8bf2108c7e743fb10b6025961a848f9dcde72fea/lib/utils.js#L420

https://github.com/Pomax/bezierjs/blob/8bf2108c7e743fb10b6025961a848f9dcde72fea/lib/utils.js#L425

I assume, it's supposed to come from the "bezierinfo" repo:

```javascript
function accept(t) {
	return 0 <= t && t <= 1;
}
```
>  https://pomax.github.io/bezierinfo/#implementing-cardano-s-algorithm-for-finding-all-real-roots

**Comment by Pomax** [comment]
Oh dang, that should be `reduce`, not `accept` O_o

let me fix that right now.

**Comment by Pomax** [comment]
v2.2.9 published
