### ISSUE TITLE
Intersection of two curves returns an exception

### ISSUE THREAD

**Issue by melalj** [Pomax/bezierjs#88]
Thanks for building this library 🙏
I would like to get the intersection of two curves (a circle and a bezier path):
<img width="282" alt="screenshot 2018-06-29 17 02 29" src="https://user-images.githubusercontent.com/3869766/42119190-458750a0-7bbe-11e8-8bea-c8795c6ba285.png">

with the following SVG:
```svg
<?xml version="1.0" encoding="UTF-8"?>
<svg width="269px" height="288px" viewBox="0 0 269 288">
    <g stroke-width="1" fill="none" fill-rule="evenodd">
        <path d="M138.406787,51.9034859 C138.406787,51.9034859 74.8695308,-25.4868408 21.9358155,9.81888414 C-30.9978998,45.1246091 32.5393566,122.514936 32.5393566,122.514936" id="Circle" stroke="#FF0000"></path>
        <path d="M133.38,286.76 C59.7162601,286.76 0,227.04374 0,153.38 C0,79.7162601 59.7162601,20 133.38,20 C207.04374,20 266.76,79.7162601 266.76,153.38 C266.76,227.04374 207.04374,286.76 133.38,286.76 Z" id="Path" stroke="#979797"></path>
    </g>
</svg>
```

When I use BezierJS to determine the interesection:
```js
const Bezier = require('bezier-js');
const circleBezier = Bezier.fromSVG(document.getElementById('Circle').getAttribute('d'));
const pathBezier = Bezier.fromSVG(document.getElementById('Path').getAttribute('d'));
const intersection = pathBezier.intersects(circleBezier);
console.log(instersection);
```

I get the following exception:
```
Uncaught TypeError: Cannot read property 'filter' of undefined
    at Bezier.<anonymous> (bezier.js:475)
    at Array.forEach (<anonymous>)
    at Bezier.extrema (bezier.js:467)
    at Bezier.reduce (bezier.js:542)
    at Bezier.intersects (bezier.js:712)
```

Any idea why it's not working?

**Comment by Pomax** [comment]
Not yet, but let's find out.

**Comment by melalj** [comment]
I suspect that the order of the beziers are high and not handled:

```
> circleBezier
Bezier {_3d: false, order: 7, points: Array(8), dims: Array(2), dimlen: 2, …}

> pathBezier
Bezier {_3d: false, order: 6, points: Array(7), dims: Array(2), dimlen: 2, …}
```

**Comment by Pomax** [comment]
Basically: yes. `fromSVG` is undocumented and was initially written to turn single curve instructions into Bezier curves, so passing it an SVG path rather than an SVG moveto+curve instruction won't work.

For SVG based path/shape work you probably want to have a look at Paper.js, which has far better shape support than bezierjs can offer.

**Comment by melalj** [comment]
Thanks, I used initially your library to be able to get the `t` for the intersection, and then split the path to remove a section of the path:
<img width="781" alt="screenshot 2018-06-29 17 40 36" src="https://user-images.githubusercontent.com/3869766/42119699-adda1bce-7bc3-11e8-9205-47f0d81969b2.png">

I want to keep only the section [AB] in red an remove the green section

**Comment by Pomax** [comment]
Hm, I can adapt `fromSVG` to return an array of Bezier curves with relatively little work, so that you can at least implement your own cross reference and intesection checks, but writing it so that it generates a proper path object, with sound intersection checks, is probably going to be more work than I can get done in the next half hour, and so would probably end up back-burnered.

**Comment by melalj** [comment]
That would be great, Thanks.
At least it shouldn't throw such exception.

**Comment by Pomax** [comment]
It's literally an undocumented function, there is no "supposed" yet =)

**Comment by melalj** [comment]
True, will dig more and see if i can come up with a solution :) Thanks for your responsiveness

**Comment by Pomax** [comment]
I've pushed up 2.2.10, which adds `Bezier.SVGtoBeziers`, which yields a `PolyBezier` object with a very limited API:

- `addCurve(<Bezier>)` grow the polybezier by a segment
- `length()` get the total length of the polybezier
- `curve(<index>)` get segment at index from the polybezier
- `bbox()` get the total bounding box for the polybezier
- `offset(<distance>)` in theory, get the combined offset curve for this polybezier, but I make no guarantees that that actually works =P

**Comment by Pomax** [comment]
The test case I use based on your example:
```
(function testSVG() {
  var circle="M138.406787,51.9034859 C138.406787,51.9034859 74.8695308,-25.4868408 21.9358155,9.81888414 C-30.9978998,45.1246091 32.5393566,122.514936 32.5393566,122.514936";
  var circleSegments = Bezier.SVGtoBeziers(circle);
  assert(circleSegments.curves.length === 2, "two sections to the circle");

  var path="M133.38,286.76 C59.7162601,286.76 0,227.04374 0,153.38 C0,79.7162601 59.7162601,20 133.38,20 C207.04374,20 266.76,79.7162601 266.76,153.38 C266.76,227.04374 207.04374,286.76 133.38,286.76 Z";
  var pathSegments = Bezier.SVGtoBeziers(path);
  assert(pathSegments.curves.length === 4, "four sections to the path");
}());
```

**Comment by melalj** [comment]
Thanks, It doesn't seem to work with SVG Arcs like:
```
M247.800 631.000 A592.200 592.200 0 1 0 1432.200 631.000 A592.200 592.200 0 1 0 247.800 631.000 Z
```

This is a circle made with Arcs instead of Bezier. I'm looking now for a way to generate a bezier SVG path (instead of SVG Arcs) from a circle.

**Comment by Pomax** [comment]
It only supports M, L, Q, C and Z.

**Comment by melalj** [comment]
Alright, I just pushed a gist to convert a circle to a set of beziers: https://gist.github.com/melalj/524fd284d4683738fe9d0cb2680deb9c

So my code looks like this:
```js
    const path = "M 403.37 465.5C 403.37 224.35590968129048 598.8559096812905 28.870000000000005 840 28.870000000000005C 1081.1440903187095 28.870000000000005 1276.63 224.35590968129048 1276.63 465.5C 1276.63 706.6440903187096 1081.1440903187095 902.13 840 902.13C 598.8559096812905 902.13 403.37 706.6440903187096 403.37 465.5Z";
    
    const pathCircle = "M840,262.0692849215183C840,262.0692849215183,623.2217248247962,125.99769017911373,458.8059257701127,226.22470571650527C294.39012671542923,326.45172125389684,511.1684018906331,462.5233159963014,511.1684018906331,462.5233159963014";

    const pathBazier = Bezier.SVGtoBeziers(path);
    const circleBezier = Bezier.SVGtoBeziers(pathCircle);

    const intersections = [];
    pathBazier.curves.forEach((pathCurve) => {
      circleBezier.curves.forEach((circleCurve) => {
        const intersection = pathCurve.intersects(circleCurve);
        if (intersection.length) intersections.concat(intersection);
      });
    });

    console.log(intersections); // outputs: []
```

It doesn't intersect with the code - but it does when when I visualize the SVG:
<img width="699" alt="screenshot 2018-07-01 10 41 58" src="https://user-images.githubusercontent.com/3869766/42137102-65fe1a86-7d1b-11e8-94d7-cad7f19401ec.png">

**Comment by Pomax** [comment]
Can we reduce this to only the segments we know should intersect, but aren't detected?

**Comment by Pomax** [comment]
Sooooo using the following code to see what the heck is going on:
```
Bezier = require("./lib/Bezier");

var script = function generateSketch(context) {
  const path = "M 403.37 465.5C 403.37 224.35590968129048 598.8559096812905 28.870000000000005 840 28.870000000000005C 1081.1440903187095 28.870000000000005 1276.63 224.35590968129048 1276.63 465.5C 1276.63 706.6440903187096 1081.1440903187095 902.13 840 902.13C 598.8559096812905 902.13 403.37 706.6440903187096 403.37 465.5Z";
  const pathSegments = Bezier.SVGtoBeziers(path);

  const circle = "M840,262.0692849215183C840,262.0692849215183,623.2217248247962,125.99769017911373,458.8059257701127,226.22470571650527C294.39012671542923,326.45172125389684,511.1684018906331,462.5233159963014,511.1684018906331,462.5233159963014";
  const circleSegments = Bezier.SVGtoBeziers(circle);

  context.strokeStyle = "red";
  context.fillStyle = "none";
  let x1, y1, x2, y2;
  [pathSegments, circleSegments].forEach( segments => {
    segments.curves.forEach( segment => {
      let LUT = segment.getLUT(100);
      context.beginPath();
      context.moveTo(LUT[0].x, LUT[0].y);
      for (let i=1; i<100; i++) {
        context.lineTo(LUT[i].x, LUT[i].y);
      }
      context.stroke();
    });
  });
};

var liveServer = require("live-server");

var params = {
    file: "test.html",
    middleware: [
      function(req, res, next) {
        console.log(req.url);

        if (req.url === "/") {
          res.writeHead(200, { 'Content-Type': 'text/html' });
          res.write(`
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <title>test</title>
    <script src="./bezier.js"></script>
  </head>
  <body>
    <h1>Testing</h1>

    <script>
      var canvas = document.createElement("canvas");
      canvas.width = canvas.height = 1000;
      var context = canvas.getContext("2d");
      document.body.append(canvas);
      setTimeout( () => {
        (${script.toString()})(context);
      },100);
    </script>
  </body>
</html>
          `);
          res.end();
        } else { next(); }
      }
    ]
};

liveServer.start(params);
```
I get the following screenshot:

![image](https://user-images.githubusercontent.com/177243/42182202-4ecc7d76-7df2-11e8-8574-7e92e5eb1461.png)

Which looks very, very wrong =)

**Comment by Pomax** [comment]
So, step 1: fix the svg parser. It was not updating the "start" coordinate for subsequent curves (that's been fixed and updated on npm). Next up: why are intersections not working...

Also note you called your circle "path" and your path "circle", so I switched that in my own test now =)

**Comment by Pomax** [comment]
![image](https://user-images.githubusercontent.com/177243/42182849-88b975e6-7df4-11e8-871c-9df7ec9ab4cf.png)

**Comment by Pomax** [comment]
Tracked the problem to `reduce()` so far, which yields an empty array (which is impossible. Either the curve is already "safe" or it should get reduced to two or more safe segments. An empty array makes no sense)

**Comment by Pomax** [comment]
Well, that's hilarious. I have no idea what `reduce` is doing but it's massively wrong.
```
[840/262, 840/262, 623/125, 458/226]
extrema: [ -0,
  0.36533333333333334,
  0.7306666666666667,
  0.8066914498141264,
  1 ]
pass curve: [840/262, 8400/2620, 8400NaN/2620NaN, 8400NaNNaN/2620NaNNaN]
[840/262, 84075.60000000000001/26223.580000000000002, 84075.60000000000001NaN/26223.580000000000002NaN, 84075.60000000000001NaNNaN/26223.580000000000002NaNNaN]
pass curve: [8400NaNNaN/2620NaNNaN, 8400NaNNaNNaN/2620NaNNaNNaN, 8400NaNNaNNaNNaN/2620NaNNaNNaNNaN, 8400NaNNaNNaNNaNNaN/2620NaNNaNNaNNaNNaN]
[8400NaNNaN/2620NaNNaN, 8400NaNNaNNaN/2620NaNNaNNaN, 8400NaNNaNNaNNaN/2620NaNNaNNaNNaN, 8400NaNNaNNaNNaNNaN/2620NaNNaNNaNNaNNaN]
pass curve: [8400NaNNaN/2620NaNNaN, 8400NaNNaNNaN/2620NaNNaNNaN, 8400NaNNaNNaNNaN/2620NaNNaNNaNNaN, 8400NaNNaNNaNNaNNaN/2620NaNNaNNaNNaNNaN]
[8400NaNNaN/2620NaNNaN, 8400NaNNaNNaN/2620NaNNaNNaN, 8400NaNNaNNaNNaN/2620NaNNaNNaNNaN, 8400NaNNaNNaNNaNNaN/2620NaNNaNNaNNaNNaN]
pass curve: [8400NaNNaN/2620NaNNaN, 840-175.05204460966544NaN/262-110.51672862453532NaN, 623-133.10408921933086/12581.47583643122677, 458/226]
[8400NaNNaN/2620NaNNaN, 8400NaNNaNNaN/2620NaNNaNNaN, 8400NaNNaNNaNNaN/2620NaNNaNNaNNaN, 8400NaNNaNNaNNaNNaN/2620NaNNaNNaNNaNNaN]
```
There is **no need** for batman.

**Comment by Pomax** [comment]
further tracked to `hull()` which is generating non numerical entries.
```
[ { x: '840', y: '262' },
  { x: '840', y: '262' },
  { x: '623', y: '125' },
  { x: '458', y: '226' },
  { x: '8400', y: '2620' },
  { x: '840-79.27733333333333', y: '262-50.050666666666665' },
  { x: '623-60.28', y: '12536.89866666666667' },
  { x: '8400NaN', y: '2620NaN' },
  { x: '840-79.27733333333333NaN',
    y: '262-50.050666666666665NaN' },
  { x: '8400NaNNaN', y: '2620NaNNaN' } ]
```

**Comment by Pomax** [comment]
further tracked to utils.lerp, which is generating said non-numerical entries.
```
lerp: { x: '8400', y: '2620' }
lerp: { x: '840-79.27733333333333', y: '262-50.050666666666665' }
lerp: { x: '623-60.28', y: '12536.89866666666667' }
lerp: { x: '8400NaN', y: '2620NaN' }
lerp: { x: '840-79.27733333333333NaN',
  y: '262-50.050666666666665NaN' }
lerp: { x: '8400NaNNaN', y: '2620NaNNaN' }
```

**Comment by Pomax** [comment]
aaaaaaaaaaaaand super false alarm, the SVG code wasn't float-casting curve arguments.

**Comment by Pomax** [comment]
There we go. 

![image](https://user-images.githubusercontent.com/177243/42185171-c7fc6c1a-7dfc-11e8-876a-d7ff939689f8.png)

The SVG parser wasn't properly casting, and your code was using `concat` without capturing the output so your empty array stayed empty.

**Comment by Pomax** [comment]
Specifically, you were using this:
```
    const intersections = [];
    pathBazier.curves.forEach((pathCurve) => {
      circleBezier.curves.forEach((circleCurve) => {
        const intersection = pathCurve.intersects(circleCurve);
        if (intersection.length) intersections.concat(intersection);
      });
    });
```
but that ` if (intersection.length) intersections.concat(intersection);` does "nothing" in that concat yields a new array, it does not modify the array in place. Also, since intersections are `t` values on the segments that you performed intersection testing on, working with them as you find it makes things easier:

```
  pathSegments.curves.forEach(c1 => {
    circleSegments.curves.forEach(c2 => {
      let intersections = c1.intersects(c2);
      showIntersection(intersections, c1, c2);
    });
  });
```

with:

```
  function showIntersection(intersections, c1, c2) {
    context.strokeStyle = 'black';
    intersections.forEach( p => {
      var times = p.split('/').map(parseFloat);
          p1 = c1.get(times[0]),
          p2 = c2.get(times[1]);
        context.beginPath();
        context.arc(p1.x,p2.y,10,0,2*Math.PI);
        context.stroke();
    });
  }
```

**Comment by melalj** [comment]
Oh wow! Indeed, the Array.concat() is immutable function.
At least, I hope I helped in some way testing a use case that improved this library.

Thanks again 🙏You totally rock!

**Comment by Pomax** [comment]
This issue opened up a good amount of code checking and making sure it worked, you rock for filing it and sticking with testing and feedback!
