### ISSUE TITLE
Prs please even if you are a primary contributor

### ISSUE THREAD

**Issue by park9140** [Pomax/bezierjs#89]
@Pomax Prs are very helpful for history of work even if you are just changing formatting or doing code cleanup.  

Also they let you stop and think about what you are doing rather than spamming a bunch of "Patch" versions out onto npm with no regard to the stability of the library.

You can give yourself a nice catch point for this by doing 
https://help.github.com/articles/enabling-branch-restrictions/

**Comment by Pomax** [comment]
PRs are not the authoritative history, the git log is. Either hit up https://github.com/Pomax/bezierjs/commits/gh-pages or use `git log` in the shell. 

PRs are just a convenient way to manage which commits ultimate make it into the git history.

**Comment by Pomax** [comment]
As for the "spamming a bunch of patches", maybe work happened that you didn't see happening that fully required those patch releases.

**Comment by park9140** [comment]
@Pomax, Sorry that my initial message was so aggressive. 

My intent above is to encourage having a fixed pattern for contributions that everyone can follow so that when something breaks due to a change users of the library can identify the issue by looking at the pr/commit log to see what was being changed when a new or changed line of code causes the library to break.  

With the commit log you have here it is very difficult to determine what changed without inspecting every line of code, and knowing a lot about this library.  Sure I can diff the branch and inspect the code  but the log messages should be describing the work at a library interface level to inform the users what might have changed that would affect them. 

As it is I have a breakage I cannot fix without a decent amount of work due to other unrelated conflicts.  That said, I would love to be able to trust this library's patch versions are important.  In order to do that I need to be able to consistently upgrade without breakage.  Additionally when I have breakage (especially for a security patch reason) I need to be able to review the history and make sense of what changed to know if it worth making the update.  

At the moment due to the lack of descriptive information about the changes in the commit/pr history, and my lack of knowledge on the exact inner workings of this library, I cannot easily make that determination.

I personally find the pr structure, and or a rebase and squash cleanup strategy to provide the cleanest most useful git history on the libraries I follow.

**Comment by park9140** [comment]
That said, I expect nothing here.  Just a suggestion.  Thanks for the great library.

**Comment by Pomax** [comment]
suggestions always appreciated, the length of the response was mostly because I take suggestions seriously and think them worth more than just "no" =)

Hopefully the library no longer gives you problems with node4
