### ISSUE TITLE
Incompatible with Create-React-App

### ISSUE THREAD

**Issue by whitebird** [Pomax/bezierjs#94]
When a project that was created with Create-React-App, the code fails to build due to the usage of a spread operator in `svg-to-beziers.js`. 

The exact line: https://github.com/Pomax/bezierjs/blob/9804fd1556f6b00b1280f98eba3bccbc1f081071/lib/svg-to-beziers.js#L11

When this line is processed by babel, the line executes. I do not know a way immediately to solve this cleanly.

**Comment by whitebird** [comment]
One solution would be to make a helper function like the one from babel.

Babel converts this:

```
function spread(x){
	const y = [...x];
}
```

Into this:

"use strict";

```
function _toConsumableArray(arr) { if (Array.isArray(arr)) { for (var i = 0, arr2 = Array(arr.length); i < arr.length; i++) { arr2[i] = arr[i]; } return arr2; } else { return Array.from(arr); } }

function spread(x) {
	var y = [].concat(_toConsumableArray(x));
}
```

**Comment by Pomax** [comment]
that line should not have landed into the repo (it's part of ES7 work). Let's change that back to ancient ES5 again.

**Comment by Pomax** [comment]
fixed, thanks for letting me know about this.
