### ISSUE TITLE
getLUT curve is not updating

### ISSUE THREAD

**Issue by gigig987** [Pomax/bezierjs#97]
The curves that uses LUT are drawn but not updated. This is also noticeable in the examples page

**Comment by Pomax** [comment]
Hm, looks like a missing `dirty` flag when the coordinates are updated leading to a stale LUT. Thanks for letting me know.

**Comment by geekofcola** [comment]
@Pomax any updates here?

**Comment by Pomax** [comment]
Not until a few minutes ago - thanks for reminding me this issue existed. The new v2.6 should fix this.
