### ISSUE TITLE
intersections with point {x, y}

### ISSUE THREAD

**Issue by dashng** [Pomax/bezierjs#98]
Do have some feature to support to check if point on the curve?

and we can set some value if distance of the point to the curve will be seemed the point on the curve?

**Comment by dashng** [comment]
@Pomax

**Comment by danmarshall** [comment]
see #25 - which would give you the T value if the point is on the curve.

**Comment by Pomax** [comment]
on a technical note, it is virtually impossible for this to ever be genuinely true (at the IEEE float precision level) so you generally just find the closest point on the curve near your point, for which a binary search works just fine.  https://pomax.github.io/bezierinfo/#projections

**Comment by dashng** [comment]
@Pomax Yes, I can get the latest point of curve by the project feature.

It worked for me, thanks for you guys quick response.
