### ISSUE TITLE
Finding curve-curve intersections: what's the best approach to weed out dupes?

### ISSUE THREAD

**Issue by joostdecock** [Pomax/bezierjs#99]
Note: This is possible related to #28 

What is the best way to go about finding curve-curve intersections without getting (almost) duplicates.

Here's an example. I am calculating intersections for these two curves:

![We should find 9 intersections](https://i.imgur.com/8Q4q3lV.png)

Running the intersections method on this takes 67 milliseconds and gives me 16 intersections:

```js
[
  "0.01416/0.01864",
  "0.08298/0.57365",
  "0.08298/0.57381",
  "0.13987/0.90866",
  "0.13987/0.90945",
  "0.46348/0.505",
  "0.46265/0.50523",
  "0.46265/0.5053",
  "0.46265/0.50515",
  "0.46348/0.50508",
  "0.35343/0.9312",
  "0.58356/0.06403",
  "0.88531/0.09458",
  "0.936/0.421",
  "0.936/0.42138",
  "0.98753/0.98138"
]
```

Obviously, some of these are (almost) the same point. So my question is: what is the best way to bring it down to the *actual 9*? It seems I have two options:

 - Round the resulting t values to 2 digits after the decimal point. That would seem to eliminate all doubles, at the expense of adding some extra inaccuracies proportionate to the length of the curve.
 - Change the `curveIntersectionThreshold` to the point where it seems to find only 9. 

For the latter, I had to bring down the `curveIntersectionThreshold` all the way to `0.0005` before it would consistenly (only) find 9 intersections:

```js
[
  "0.0141/0.01869",
  "0.08293/0.57374",
  "0.13977/0.90899",
  "0.46304/0.50516",
  "0.35348/0.93118",
  "0.58371/0.06391",
  "0.8854/0.09454",
  "0.9358/0.42129",
  "0.98745/0.98147"
]
```

While this increased execution time to 81 milliseconds, I do think I prefer this solution to rounding the t values.

But, I don't pretend to fully understand the impact of this change. Which is why I was wondering what your suggested course of action would be to weed out *dupes* in intersections.

Thank you for your great work.
joost

**Comment by Pomax** [comment]
I typically go with 1, using something like:

```
// find all the roots
let objform =roots.map(v => {
  let s = v.split('/').map(parseFloat);
  return {t1:s[0], t2: s[1] };
});

// aggressively filter out duplicates
objform.filter( (v,i) => i===0? true : Math.abs(v.t1-objform[i-1].t1)>0.01)
```

Returning strings made sense way back when but with modern JS that code really should get a rewrite to just return a normal object... =(

**Comment by joostdecock** [comment]
Ok, thanks for your input. I'll give that advice a spin.

And you're too hard on yourself 😉
